### ISSUE TITLE
textarea or input lost focus time to time 

### ISSUE THREAD

**Issue by culmencasa** [vincepare/iframeTracker-jquery#22] opened 2018-04-11 08:36 UTC
when user input, mouse does't move, but text box will lost focus, maybe due to input method, but how can i fix this by filtering input or textarea element

**Comment by vincepare** [comment] 2018-04-14 12:37
Please give more information :

* jQuery version
* iframeTracker version
* Browser and OS
* Provide a minimal test case (use tools like [jsbin](https://jsbin.com), [jsfiddle](https://jsfiddle.net) or [codepen](https://codepen.io/))

**Comment by culmencasa** [comment] 2018-04-17 06:17
jquery version: 2.2.4
iframeTracker version: 2.0.0
Browser and OS: chrome in Windows 10


i have resolved my problem by adding a statement below to avoid those anything don't know what to trigger mouseout event.

mouseoutListener: function(e) {
         if (document.activeElement == this) { return false; }
        

         e.data.handler.over = false;
         $.iframeTracker.focusRetriever.focus();

         ......
}

thanks.

**Comment by vincepare** [comment] 2018-04-21 19:42
I think it's a duplicate of #2, you should try to update to 2.1.0 instead of hacking `mouseoutListener`.

**Comment by culmencasa** [comment] 2018-04-22 13:00
thanks. i'll update it.

**Closed as completed** 2020-11-26 01:32 UTC
